BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
               ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "foxtalk"
BBFILE_PATTERN_foxtalk = "^${LAYERDIR}/"
BBFILE_PRIORITY_foxtalk = "7"
LAYERDEPENDS_foxtalk = "core"
LAYERSERIES_COMPAT_foxtalk = "scarthgap"

