#@TYPE: Machine
#@NAME: Luckfox Pico Mini
#@Description: Luckfox Pico Mini with Rockhip RV1103G1

require conf/machine/include/arm/armv7a/tune-cortexa7.inc

MACHINE_FEATURES = "usbhost usbgadget wifi ext2"

PREFERRED_PROVIDER_virtual/kernel = "linux-luckfox"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-luckfox"

UBOOT_MACHINE = "luckfox_rv1106_uboot_defconfig"

SERIAL_CONSOLES = "1500000;ttyS0"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "rv1103g-luckfox-pico-mini-b.dtb"

IMAGE_FSTYPES = "ext4"

