BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "luckfox-bsp"
BBFILE_PATTERN_luckfox-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_luckfox-bsp = "6"
LAYERDEPENDS_luckfox-bsp = "core"
LAYERSERIES_COMPAT_luckfox-bsp = "scarthgap"

